### ISSUE TITLE
LAMA interface doesn't seem to parse plans correctly

### ISSUE THREAD

**Issue by alex-mitrevski** [b-it-bots/ROSPlan#5]
When using the LAMA planner interface with my storing groceries planning domain (https://github.com/b-it-bots/mas_domestic_robotics/pull/206) and [this problem](https://github.com/b-it-bots/ROSPlan/files/4114067/problem.txt), I'm getting a `Plan was unsolvable` error from ROSPlan, even though the problem is actually solvable (which I can confirm by calling the planner independently, but also by verifying the planner output after calling the planner through ROSPlan).

Here's the ROSPlan output after calling the interface

```
[ INFO] [1580063310.038734227]: KCL: (/rosplan_problem_interface) (problem.pddl) Generating problem file.
[ INFO] [1580063310.399983379]: KCL: (/rosplan_problem_interface) (problem.pddl) The problem was generated.
[ INFO] [1580063310.400479299]: KCL: (/rosplan_planner_interface) Problem received.
[ INFO] [1580063310.409530323]: KCL: (/rosplan_planner_interface) (problem.pddl) Writing problem to file.
[ INFO] [1580063310.412687553]: KCL: (/rosplan_planner_interface) (problem.pddl) Running: cd /path/to/mas_domestic_robotics/mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_store_groceries/config/plan/; /path/to/ROSPlan/rosplan_planning_system/common/bin/fast-downward/fast-downward.py --search-time-limit 10 --alias seq-sat-lama-2011 --plan-file plan.txt /path/to/mas_domestic_robotics/mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_store_groceries/config/domain.pddl /path/to/mas_domestic_robotics/mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_store_groceries/config/problem.pddl > /path/to/mas_domestic_robotics/mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_store_groceries/config/plan.pddl

[ INFO] [1580063310.544644107]: KCL: (/rosplan_planner_interface) (problem.pddl) Planning complete
Best plan is:;
[ INFO] [1580063310.549507611]: KCL: (/rosplan_planner_interface) (problem.pddl) Plan was unsolvable.
```

The actual output of the planner, which confirms that a plan was indeed found, is given [here](https://github.com/b-it-bots/ROSPlan/files/4114079/planner_output.txt)

Just for the record, the command I've specified for invoking the planner is

```
$(find rosplan_planning_system)/common/bin/fast-downward/fast-downward.py --search-time-limit 10 --alias seq-sat-lama-2011 --plan-file plan.txt DOMAIN PROBLEM
```

Any ideas what the problem might be?

**Comment by DharminB** [comment]
The command you have specified is not supported. The command should not contain `--plan-file plan.txt` but should look like the one I mentioned [here](https://github.com/b-it-bots/ROSPlan/pull/3#issue-359261381). This is because I am using the default argument for `--plan-file` to post process the plan files.

**Comment by alex-mitrevski** [comment]
That was indeed the problem. Thanks @DharminB!

**Comment by rhasel4s** [comment]
Hey, 

just have a few question while looking at the code in the lama interface, why is the planner called several times ? Or do i get something wrong ? 

Cheers Rohan

**Comment by alex-mitrevski** [comment]
Hi @rhasel4s 

The planner command is only run once. I think what you're referring to are the different calls to the `runCommand` function - there are three of those:
1. with the first call, a temporary directory is created for saving the results of the planner
2. the second call executes the planner command
3. the third call finds the file corresponding to the best found plan (the planner generates multiple files, one per plan found)

Hope that helps.
